import test from "node:test";
import assert from "node:assert/strict";

import { parseFormDocument } from "../src/core/parser/formParser";
import { GADGET_KIND } from "../src/core/model";
import { loadFixture } from "./helpers/loadFixture";

test("parses fixtures/smoke/01-window-basic.pbf", () => {
  const text = loadFixture("fixtures/smoke/01-window-basic.pbf");
  const doc = parseFormDocument(text);

  assert.ok(doc.window, "Expected a parsed window.");
  assert.equal(doc.window?.id, "#FrmMain");
  assert.equal(doc.window?.variable, "FrmMain");
  assert.equal(doc.window?.pbAny, false);
  assert.equal(doc.window?.w, 220);
  assert.equal(doc.window?.h, 140);
  assert.equal(doc.gadgets.length, 0);
  assert.ok(doc.meta.enums);
  assert.deepEqual(doc.meta.enums?.windows, ["#FrmMain"]);
  assert.deepEqual(doc.meta.enums?.gadgets, []);
});

test("parses fixtures/smoke/03-gadgets-basic.pbf", () => {
  const text = loadFixture("fixtures/smoke/03-gadgets-basic.pbf");
  const doc = parseFormDocument(text);

  assert.ok(doc.window, "Expected a parsed window.");
  assert.equal(doc.window?.id, "#FrmGadgets");
  assert.equal(doc.window?.variable, "FrmGadgets");
  assert.equal(doc.window?.pbAny, false);
  assert.equal(doc.gadgets.length, 3);

  const textGadget = doc.gadgets.find((g) => g.kind === GADGET_KIND.TextGadget);
  assert.ok(textGadget, "Expected one TextGadget.");
  assert.equal(textGadget?.id, "#LblName");

  const buttonGadget = doc.gadgets.find((g) => g.kind === GADGET_KIND.ButtonGadget);
  assert.ok(buttonGadget, "Expected one ButtonGadget.");
  assert.equal(buttonGadget?.id, "#BtnOk");

  const pbAnyGadgets = doc.gadgets.filter((g) => g.pbAny);
  assert.equal(pbAnyGadgets.length, 1);
  assert.equal(pbAnyGadgets[0]?.kind, GADGET_KIND.StringGadget);
  assert.equal(pbAnyGadgets[0]?.id, "gInput");
  assert.equal(pbAnyGadgets[0]?.variable, "gInput");
});

test("parses samples/sample.pbf as a real-world smoke case", () => {
  const text = loadFixture("samples/sample.pbf");
  const doc = parseFormDocument(text);

  assert.ok(doc.window, "Expected a parsed window.");
  assert.ok(doc.window?.id.length, "Expected a non-empty window id.");
  assert.ok(doc.gadgets.length > 0, "Expected at least one parsed gadget.");
});


test("parses OpenWindow caption literals and keeps title as compatibility alias", () => {
  const text = `; Form Designer for PureBasic - 6.20
;
; EnableExplicit
;
;   Warning: This file is generated by the Form Designer.
;            Manual changes will be lost after recompilation!

Enumeration FormWindow
  #FrmMain
EndEnumeration

Enumeration FormGadget
EndEnumeration

Procedure OpenFrmMain(x = 0, y = 0, width = 220, height = 140)
  OpenWindow(#FrmMain, x, y, width, height, "Window Basic")
EndProcedure
`;

  const doc = parseFormDocument(text);
  assert.ok(doc.window, "Expected a parsed window.");
  assert.equal(doc.window?.caption, "Window Basic");
  assert.equal(doc.window?.captionVariable, false);
  assert.equal(doc.window?.title, "Window Basic");
  assert.equal(doc.window?.source?.line, 15);
});

test("parses OpenWindow caption variables and normalizes parent references", () => {
  const text = `; Form Designer for PureBasic - 6.20
;
; EnableExplicit
;
;   Warning: This file is generated by the Form Designer.
;            Manual changes will be lost after recompilation!

Enumeration FormWindow
  #FrmParent
  #FrmChild
EndEnumeration

Enumeration FormGadget
EndEnumeration

Procedure OpenFrmChild(x = 0, y = 0, width = 220, height = 140)
  OpenWindow(#FrmParent, 0, 0, 100, 100, "Parent")
  OpenWindow(#FrmChild, x, y, width, height, Title$, #PB_Window_SystemMenu, WindowID(#FrmParent))
EndProcedure
`;

  const doc = parseFormDocument(text);
  assert.ok(doc.window, "Expected a parsed window.");
  assert.equal(doc.window?.id, "#FrmChild");
  assert.equal(doc.window?.caption, "Title$");
  assert.equal(doc.window?.captionVariable, true);
  assert.equal(doc.window?.title, "Title$");
  assert.equal(doc.window?.parent, "#FrmParent");
});

test("normalizes non-WindowID OpenWindow parent references with leading equals", () => {
  const text = `; Form Designer for PureBasic - 6.20
;
; EnableExplicit
;
;   Warning: This file is generated by the Form Designer.
;            Manual changes will be lost after recompilation!

Enumeration FormWindow
  #FrmChild
EndEnumeration

Enumeration FormGadget
EndEnumeration

Procedure OpenFrmChild()
  OpenWindow(#FrmChild, 0, 0, 100, 100, "Child", 0, ParentWindow)
EndProcedure
`;

  const doc = parseFormDocument(text);
  assert.ok(doc.window, "Expected a parsed window.");
  assert.equal(doc.window?.parent, "=ParentWindow");
});


test("parses HideWindow, DisableWindow and SetWindowColor for enum windows", () => {
  const text = `; Form Designer for PureBasic - 6.20
;
; EnableExplicit
;
;   Warning: This file is generated by the Form Designer.
;            Manual changes will be lost after recompilation!

Enumeration FormWindow
  #FrmMain
EndEnumeration

Enumeration FormGadget
EndEnumeration

Procedure OpenFrmMain()
  OpenWindow(#FrmMain, 0, 0, 100, 100, "Main")
  HideWindow(#FrmMain, 1)
  DisableWindow(#FrmMain, 1)
  SetWindowColor(#FrmMain, RGB(17, 34, 51))
EndProcedure
`;

  const doc = parseFormDocument(text);
  assert.ok(doc.window, "Expected a parsed window.");
  assert.equal(doc.window?.hidden, true);
  assert.equal(doc.window?.disabled, true);
  assert.equal(doc.window?.color, 0x332211);
});

test("parses HideWindow, DisableWindow and SetWindowColor for #PB_Any windows assigned to a variable", () => {
  const text = `; Form Designer for PureBasic - 6.20
;
; EnableExplicit
;
;   Warning: This file is generated by the Form Designer.
;            Manual changes will be lost after recompilation!

Enumeration FormWindow
EndEnumeration

Enumeration FormGadget
EndEnumeration

Procedure OpenFrmMain()
  win = OpenWindow(#PB_Any, 0, 0, 100, 100, "Main")
  HideWindow(win, 0)
  DisableWindow(win, 1)
  SetWindowColor(win, $112233)
EndProcedure
`;

  const doc = parseFormDocument(text);
  assert.ok(doc.window, "Expected a parsed window.");
  assert.equal(doc.window?.id, "win");
  assert.equal(doc.window?.hidden, false);
  assert.equal(doc.window?.disabled, true);
  assert.equal(doc.window?.color, 0x112233);
});
