import test from "node:test";
import assert from "node:assert/strict";

import { parseFormDocument } from "../src/core/parser/form-parser";
import { applyWindowEventProcUpdate, applyWindowEventUpdate, applyWindowGenerateEventLoopUpdate } from "../src/core/emitter/patch-emitter";
import { FakeTextDocument } from "./helpers/fakeTextDocument";
import { applyWorkspaceEditToText } from "./helpers/applyWorkspaceEdit";
import type { TextDocument } from "vscode";

function patchAndReparse(text: string, editFactory: (document: TextDocument) => ReturnType<typeof applyWindowEventUpdate>) {
  const document = new FakeTextDocument(text);
  const edit = editFactory(document.asTextDocument());
  assert.ok(edit, "Expected a WorkspaceEdit result.");
  const patchedText = applyWorkspaceEditToText(text, edit!);
  return {
    patchedText,
    parsed: parseFormDocument(patchedText),
  };
}

const PLAIN_WINDOW_TEXT = `; Form Designer for PureBasic - 6.40
; Warning: this file uses a strict syntax, if you edit it, make sure to respect the Form Designer limitation or it won't be opened again.

;
; This code is automatically generated by the Form Designer.
; Manual modification is possible to adjust existing commands, but anything else will be dropped when the code is compiled.
; Event procedures need to be put in another source file.
;

Enumeration FormWindow
  #FrmMain
EndEnumeration


Procedure OpenFrmMain(x = 0, y = 0, width = 220, height = 140)
  OpenWindow(#FrmMain, x, y, width, height, "Window Basic")
EndProcedure
`;

const EXISTING_EVENT_PROC_TEXT = `; Form Designer for PureBasic - 6.40
; Warning: this file uses a strict syntax, if you edit it, make sure to respect the Form Designer limitation or it won't be opened again.

;
; This code is automatically generated by the Form Designer.
; Manual modification is possible to adjust existing commands, but anything else will be dropped when the code is compiled.
; Event procedures need to be put in another source file.
;

Enumeration FormWindow
  #FrmEventsParent
EndEnumeration

Declare HandleFrmEventsParent(Event, Window)


Procedure OpenFrmEventsParent(x = 0, y = 0, width = 280, height = 170)
  OpenWindow(#FrmEventsParent, x, y, width, height, "Events Parent")
EndProcedure

Procedure FrmEventsParent_Events(event)
  Select event
    Case #PB_Event_CloseWindow
      ProcedureReturn #False

    Case #PB_Event_Menu
      Select EventMenu()
      EndSelect

    Case #PB_Event_Gadget
      Select EventGadget()
      EndSelect

    Default
      HandleFrmEventsParent(event, #FrmEventsParent)
  EndSelect
  ProcedureReturn #True
EndProcedure
`;

const LEGACY_EVENT_FILE_TEXT = `; Form Designer for PureBasic - 6.30
XIncludeFile "events/form-events.pbi"

Enumeration FormWindow
  #FrmEventsParent
EndEnumeration

Procedure OpenFrmEventsParent(x = 0, y = 0, width = 280, height = 170)
  OpenWindow(#FrmEventsParent, x, y, width, height, "Events Parent")
EndProcedure
`;

test("roundtrips window event include insertion only in isolated legacy/extension input with an existing _Events procedure", () => {
  const { patchedText, parsed } = patchAndReparse(EXISTING_EVENT_PROC_TEXT, (document) =>
    applyWindowEventUpdate(document, "#FrmEventsParent", {
      eventFileRaw: '"events/form-events-new.pbi"',
    })
  );

  assert.match(patchedText, /XIncludeFile "events\/form-events-new\.pbi"/);
  assert.equal(parsed.window?.eventFile, "events/form-events-new.pbi");
});

test("roundtrips window event include removal from isolated legacy syntax", () => {
  const { patchedText, parsed } = patchAndReparse(LEGACY_EVENT_FILE_TEXT, (document) =>
    applyWindowEventUpdate(document, "#FrmEventsParent", {})
  );

  assert.doesNotMatch(patchedText, /XIncludeFile/);
  assert.equal(parsed.window?.eventFile, undefined);
});

test("returns no edit when removing a missing window event include from isolated extension input", () => {
  const document = new FakeTextDocument(PLAIN_WINDOW_TEXT);
  const edit = applyWindowEventUpdate(document.asTextDocument(), "#FrmMain", {});
  assert.equal(edit, undefined);
});

test("roundtrips window event include insertion only in isolated extension input", () => {
  const { patchedText, parsed } = patchAndReparse(PLAIN_WINDOW_TEXT, (document) =>
    applyWindowEventUpdate(document, "#FrmMain", {
      eventFileRaw: '"events/form-main.pbi"',
    })
  );

  assert.match(patchedText, /XIncludeFile "events\/form-main\.pbi"(?:\r?\n)+Procedure OpenFrmMain/);
  assert.equal(parsed.window?.eventFile, "events/form-main.pbi");
  assert.equal(parsed.window?.eventProc, undefined);
  assert.equal(parsed.window?.generateEventLoop, undefined);
});

test("roundtrips combined window event bootstrap updates only in isolated extension input", () => {
  let patchedText = PLAIN_WINDOW_TEXT;

  let document = new FakeTextDocument(patchedText);
  let edit = applyWindowEventUpdate(document.asTextDocument(), "#FrmMain", {
    eventFileRaw: '"events/form-main.pbi"',
  });
  assert.ok(edit, "Expected event include edit.");
  patchedText = applyWorkspaceEditToText(patchedText, edit!);

  document = new FakeTextDocument(patchedText);
  edit = applyWindowGenerateEventLoopUpdate(document.asTextDocument(), "#FrmMain", true);
  assert.ok(edit, "Expected generateEventLoop edit.");
  patchedText = applyWorkspaceEditToText(patchedText, edit!);

  document = new FakeTextDocument(patchedText);
  edit = applyWindowEventProcUpdate(document.asTextDocument(), "#FrmMain", "HandleFrmMain");
  assert.ok(edit, "Expected window event proc edit.");
  patchedText = applyWorkspaceEditToText(patchedText, edit!);

  const parsed = parseFormDocument(patchedText);

  assert.match(patchedText, /XIncludeFile "events\/form-main\.pbi"(?:\r?\n)+Procedure OpenFrmMain/);
  assert.match(patchedText, /Procedure FrmMain_Events\(event\)\s+Select event/s);
  assert.match(patchedText, /Case #PB_Event_Gadget\s+Select EventGadget\(\)\s+EndSelect\s+Default\s+HandleFrmMain\(event, #FrmMain\)/s);
  assert.equal(parsed.window?.eventFile, "events/form-main.pbi");
  assert.equal(parsed.window?.generateEventLoop, true);
  assert.equal(parsed.window?.eventProc, "HandleFrmMain");
  assert.equal(parsed.window?.hasEventGadgetBlock, true);
  assert.equal(parsed.window?.hasEventGadgetCaseBranches, undefined);
});
